### ISSUE TITLE
Publish?

### ISSUE THREAD

**Issue by benjick** [VeliovGroup/meteor-autoform-file#1]
Can you publish this or is something missing? 

Cheers

**Comment by dr-dimitru** [comment]
Hi @benjick 
This package is far away from stable.
Actually we just cloned it.

I think it will be published during 1-2 weeks

**Comment by benjick** [comment]
Thanks @dr-dimitru! :)

**Comment by thearabbit** [comment]
I waiting this...
👍

**Comment by Neobii** [comment]
I'm going to have an example of autoform integration pretty soon with
GridFS.  It will get it further to the finish line.

**Comment by Neobii** [comment]
Here's a stripped down example of how I'm using it in autoform.  https://github.com/Neobii/files-gridfs-autoform-example .  There's a bunch of limitations right now, but hopefully ya'll can help me work them out and eventually make an autoform field input out of this.

**Comment by Neobii** [comment]
Hey ya'll I just pushed a version that works, but is not complete, check it out, hopefully some pull requests will start coming in!

**Comment by thearabbit** [comment]
Thanks, I will try soon.

**Comment by dr-dimitru** [comment]
Published: https://atmospherejs.com/ostrio/autoform-files
