### ISSUE TITLE
Sanitized error class

### ISSUE THREAD

**Issue by ifalldev** [VeliovGroup/meteor-autoform-file#11]
I'm using `aldeed:autoform`, `ostrio:files` and `ostrio:autoform-files`(as expected) to manage my forms.

While I worked **just with the** `ostrio:files` to upload images everything went fine, but when I put `autoform-files` on the scene I got this error after I've select the file: 

> Match error: Expected plain object

**Comment by dr-dimitru** [comment]
1. What versions you're on? (`meteor`, `autoform-files`)
 2. Where and when this error occurs?

**Comment by ifalldev** [comment]
I fixed it!

**Comment by dr-dimitru** [comment]
@ifalldev great,

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
