### ISSUE TITLE
Old image has not been removed from the collection after editing file field

### ISSUE THREAD

**Issue by aposidelov** [VeliovGroup/meteor-autoform-file#14]
Instead a new image is created after every editing of file field.

**Comment by dr-dimitru** [comment]
Hello @aposidelov ,

Yes, currently it works this way.
I'll try to fix this in next release.

Btw how you're editing field? Have you clicked on remove link before upload new file?

**Comment by aposidelov** [comment]
Hi @dr-dimitru,
Yes, there's only way to replace a picture is to click remove link and upload new picture. Also I has some problem related with pictures.
I have simple data model: Users can create Posts and every User has Image picture. Also I have a List page where all Posts are shown and under each Post theer's an Image of author.
![metim](https://cloud.githubusercontent.com/assets/2487197/21171897/28cb25cc-c1cf-11e6-98d8-5088426e603f.png)
And I want to have in my local collection only Users and Image that are related to current Posts that is shown on List page.
So here is how publish function looks like:
```javascript
Meteor.publish('posts.all.main', function() {         
    var userIds = [], imageIds = [];

    userIds = Posts
                .find({},{author:1})
                .map(function(item) { return item.author; });

    imageIds = Meteor.users
                .find({},{fields: { "profile.userPicture":1}})
                .map(function(item) { return item.profile.userPicture; });    
       
    return [
        Posts.find({}),
        Meteor.users
            .find({_id : {$in : userIds}}, 
                { fields: { 
                    "profile.userPicture":1, 
                    "profile.firstName":1, 
                    "profile.lastName":1, 
                    "status.online":1, 
                    'status.lastLogin.date':1 
                }}
            ),
        Images.find({_id: {$in : imageIds}}).cursor
    ];
});
```
And it gets exactly proper data and works fine till I try to edit some avatar (I do it from bootstrap modal window on same page so List page is not refreshed and Modal window and List page have template level subscription).
So after editing user's picture what happens: After some user picture is changed and modal window is closed I can see that this user has profile.userPicture field changed but new image is not taken by subscription. It's like User editing provoked to update all User collections but not Image collcections. What can you recommend how to make to update Image collection in this situation?

**Comment by dr-dimitru** [comment]
Hi @aposidelov ,

What your collection options? Is `allowClientCode` is `true`?

**Comment by aposidelov** [comment]
false

**Comment by dr-dimitru** [comment]
Set it to true, - issue should be solved then.
To add protection layer, use `onBeforeRemove` or `protected` hooks.

**Comment by aposidelov** [comment]
yes, it's helped with removing images, thank you!

**Comment by dr-dimitru** [comment]
Glad we have solved it. Thank you for the patience.

**Comment by aposidelov** [comment]
and how about above issue with binding posts -> users -> images. publish function that pick images by users that are authors of posts. And after image update user picture id has been updated and image is not taken from server. How do you recommend to solve this ?

**Comment by dr-dimitru** [comment]
You need to update/republish `posts.all.main` as `userIds` and `imageIds` is not reactive sources.

You're better to copy fileObj into user's record.

```js
var cursor = Images.find({});
cursor.observe({
  added: function (doc) {
    var user = Meteor.users.findOne({_id: doc.userId});
    if (user) {
      Meteor.users.update({_id: doc.userId}, {$set: {'profile.userPicture': _.omit(doc, '_prefix', '_storagePath', 'path', 'size', 'versions')}});
    }
  },
  removed: function (doc) {
    var user = Meteor.users.findOne({_id: doc.userId});
    if (user) {
      Meteor.users.update({_id: doc.userId}, {$unset: {'profile.userPicture': ''}});
    }
  }
});
```

Then in template just use:
```html
<img src="{{fileURL user.profile.userPicture}}" />
```
