### ISSUE TITLE
Uncaught TypeError: upload.on is not a function

### ISSUE THREAD

**Issue by EasyFormsSam** [VeliovGroup/meteor-autoform-file#15]
I am Getting this error when I try to add a file:

`Uncaught TypeError: upload.on is not a function`  
at `ostrio_autoform-files.js?hash=d7ab430…:247`

**Comment by dr-dimitru** [comment]
Hi @EasyFormsSam ,

 1. What version of Meteor, Meteor-Files and autoform-file are you using?
 2. Mac, Win or Linux? Browser?
 3. What is your setup? Can I see some code?

**Comment by EasyFormsSam** [comment]
Thank You for the quick response, I am on the latest stable release of all 3 I believe, I installed Meteor-Files and autoform-file just earlier this week. 

I am running Chrome on Windows 10, and the App is running on a digital ocean Ubuntu 14.04 server

Im not sure what code you want to see, 
here is what I am currently using to try this:
```
	var Plans = new FilesCollection({
		collectionName: 'Plans',
		allowClientCode: false, // Disallow remove files from Client,
		onBeforeUpload: function (file) {
			// Allow upload files under 10MB, and only in png/jpg/jpeg formats
			if (file.size <= 10485760 && /png|jpg|jpeg|pdf/i.test(file.ext)) {
				return true;
			} else {
				return 'Please upload image, with size equal or less than 10MB';
			}
		}

	});

	if (Meteor.isClient) {
		Meteor.subscribe('files.plans.all');
	}

	if (Meteor.isServer) {
		Plans.allow({
			insert: function() {
				return true;
			},
			update: function() {
				return true;
			},
			remove: function() {
				return true;
			}
		});
		
		Meteor.publish('files.plans.all', function () {
			return Plans.collection.find({});
		});


	}

```

and in my schema: 

```
	floorPlan: {
		type: String,
		autoform:{
			afFieldInput:{
				type: 'fileUpload',
				collection: "Plans",
				label: "Floor Plan"		
	              }
		},
		optional:true


	}
```
And in the {{autoform}} 
( insert )


`	{{> afQuickField name="floorPlan"}}
`

**Comment by dr-dimitru** [comment]
@EasyFormsSam could you please pass `debug: true` into FilesCollection Constructor and post here all logs from both *Client* and *Server*

**Comment by EasyFormsSam** [comment]
I did not get any additional logs, however sorry but I left out in the original that I am also getting `insert failed: Access denied`

**Comment by dr-dimitru** [comment]
Do you have stack trace for `insert failed: Access denied` ?

**Comment by EasyFormsSam** [comment]
There is just this message,  ` insert failed: Access denied - meteor.js:930 `
Im not sure if that helps

**Comment by EasyFormsSam** [comment]
the upload.on issue has this information


```
change [data-files-collection-upload]	@	ostrio_autoform-files.js:247
(anonymous function)	@	blaze.js:3718
Template._withTemplateInstanceFunc	@	blaze.js:3687
(anonymous function)	@	blaze.js:3717
(anonymous function)	@	blaze.js:2560
Blaze._withCurrentView	@	blaze.js:2214
(anonymous function)	@	blaze.js:2559
(anonymous function)	@	blaze.js:835
dispatch	@	jquery.js:4723
elemData.handle	@	jquery.js:4391
```

**Comment by EasyFormsSam** [comment]
I have looked into mongo and 2 collections are being created, "Plans" and "plans"

**Comment by EasyFormsSam** [comment]
removed the var when defining Plans fixed the issue
