### ISSUE TITLE
Issues with meteor@1.3.5.1 (Version Constraint)

### ISSUE THREAD

**Issue by kenshinman** [VeliovGroup/meteor-autoform-file#18]
Hello @dr-dimitru , Thanks for this wonderful package.
I am working on an app using meteor 1.3.5.1 and `ostrio:files` works perfectly well but when add `ostrio:autoform-files` i get this error:

    `Conflict: Constraint ostrio:files@1.7.6 is not satisfied by ostrio:files 1.6.6.
     Constraints on package "ostrio:files":
     * ostrio:files@1.7.6 <- ostrio:autoform-files 1.0.9`
What version of this package can I install to make it compatible with my current `ostrio:files`? Thanks

**Comment by dr-dimitru** [comment]
Hello @kenshinman ,

Latest `ostrio:files` requires Meteor@1.4.*, while `ostrio:autoform-files` has dependency for latest `ostrio:files`.

To solve this without upgrading `Meteor` to `1.4.*` clone this repository to `yourapp/packages/` and change `ostrio:files` version [here](https://github.com/VeliovGroup/meteor-autoform-file/blob/master/package.js#L18) to currently installed version.

**Comment by kenshinman** [comment]
@dr-dimitru Thanks a lot, I'll give it a try and get back to you.

**Comment by kenshinman** [comment]
@dr-dimitru done this, but do I still leave the `ostrio:autoform-files` in the packages list?

**Comment by kenshinman** [comment]
Hello @dr-dimitru, Thanks for sticking with me.
I have done as you instructed now, i'm getting this error in the console 
    `errorClass
errorType
:
"Match.Error"
message
:
"Match error: Expected plain object"
path
:
""
sanitizedError
:
errorClass
stack
:
"Error↵    at exports.check (http://localhost:3000/packages/check.js?hash=bf95dee84c2be9008274d2385c637659760b9057:67:15)↵    at new UploadInstance (http://localhost:3000/packages/ostrio_files.js?hash=ca8aebee86f897f5101171ceb14fd08e066f1bb1:2593:7)↵    at FilesCollection.exports.FilesCollection.FilesCollection.insert (http://localhost:3000/packages/ostrio_files.js?hash=ca8aebee86f897f5101171ceb14fd08e066f1bb1:2551:12)↵    at Blaze.TemplateInstance._insert (http://localhost:3000/packages/yogiben_autoform-file.js?hash=3d363e8d810a0573e329d6dd6afecd4518e0db13:244:23)↵    at Object.fileuploadchange .js-file (http://localhost:3000/packages/yogiben_autoform-file.js?hash=3d363e8d810a0573e329d6dd6afecd4518e0db13:345:14)↵    at http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:3718:20↵    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:3687:12)↵    at Blaze.View.<anonymous> (http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:3717:25)↵    at http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:2560:30↵    at Object.Blaze._withCurrentView (http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:2214:12)"
__proto__
:
Error`

What is the cause of this please? Thanks

**Comment by dr-dimitru** [comment]
Collection is not in global spacename on Client.

How do you define FilesCollection?

**Comment by kenshinman** [comment]
@dr-dimitru 
in my oroject's directory `lib/collections/postImages.js`

Here's the code:
    `
    var thePostImages = new FilesCollection({
    debug: true,
  storagePath: function (){
    return '/.uploads';
  } ,
  collectionName: 'thePostImages',
  allowClientCode: true, // Required to let you remove uploaded file
  onBeforeUpload: function (file) {
    // Allow upload files under 10MB, and only in png/jpg/jpeg formats
    if (file.size <= 10485760 && /png|jpg|jpeg/i.test(file.ext)) {
      return true;
    } else {
      return 'Please upload image, with size equal or less than 10MB';
    }
  }
   })`

**Comment by dr-dimitru** [comment]
1. omit `var` before `thePostImages1`
 2. If #1 not helped, use - `this.thePostImages1 = new FilesCollection({/*...*/});`

**Comment by kenshinman** [comment]
Same thing after trying both
```
errorClass
errorType
:
"Match.Error"
message
:
"Match error: Expected plain object"
path
:
""
sanitizedError
:
errorClass
stack
:
"Error↵    at exports.check (http://localhost:3000/packages/check.js?hash=bf95dee84c2be9008274d2385c637659760b9057:67:15)↵    at new UploadInstance (http://localhost:3000/packages/ostrio_files.js?hash=ca8aebee86f897f5101171ceb14fd08e066f1bb1:2593:7)↵    at FilesCollection.exports.FilesCollection.FilesCollection.insert (http://localhost:3000/packages/ostrio_files.js?hash=ca8aebee86f897f5101171ceb14fd08e066f1bb1:2551:12)↵    at Blaze.TemplateInstance._insert (http://localhost:3000/packages/yogiben_autoform-file.js?hash=3d363e8d810a0573e329d6dd6afecd4518e0db13:244:23)↵    at Object.fileuploadchange .js-file (http://localhost:3000/packages/yogiben_autoform-file.js?hash=3d363e8d810a0573e329d6dd6afecd4518e0db13:345:14)↵    at http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:3718:20↵    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:3687:12)↵    at Blaze.View.<anonymous> (http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:3717:25)↵    at http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:2560:30↵    at Object.Blaze._withCurrentView (http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:2214:12)"
__proto__
:
Error
```

**Comment by dr-dimitru** [comment]
Looks much better to me.
Now something is wrong with what you're passing to `UploadInstance` (when you call `.insert()`)

**Comment by kenshinman** [comment]
I'm using autoform so, I'm not in charge of the `insert()` event. All I am doing is just upload the file

**Comment by dr-dimitru** [comment]
Ah... sure... I guess this is incompatibility issue

Now you need to try every version below `v1.0.2` 
Click on "Source Code" to download archive [here](https://github.com/VeliovGroup/meteor-autoform-file/releases), then place it to `pros/packages` as you did before

**Comment by kenshinman** [comment]
Deleting the previous one I guess...

**Comment by kenshinman** [comment]
:( not working :(. I downloaded the zip file and extracted it into `myapp/packages` but I still get the same error.

I also duplicated the app and updated it to METEOR@1.4.2.3 and when i tried uploading, I got the same error in the console

**Comment by dr-dimitru** [comment]
1. Have you seen [this example](https://github.com/VeliovGroup/files-gridfs-autoform-example)?
 2. Is it same error on latest meteor, and latest package version?
 3. Could you copy-paste thrown error one more time? (*To make sure it's same*)

**Comment by kenshinman** [comment]
Hi @dr-dimitru , i'm back. 😄 . Thanks for all the help so far.

I just want to mention that I already `ostrio:files` and it's working perfectly. I tried using the same collection in the `collection: ` field but I still get the same error. Here is the error again.

```
errorClasserrorType: "Match.Error"message: "Match error: Expected plain object"path: ""sanitizedError: errorClassdetails: undefinederror: 400errorType: "Meteor.Error"message: "Match failed [400]"reason: "Match failed"stack: "Error↵    at errorClass.<anonymous> (http://localhost:3000/packages/check.js?hash=bf95dee84c2be9008274d2385c637659760b9057:113:27)↵    at new errorClass (http://localhost:3000/packages/meteor.js?hash=ae8b8affa9680bf9720bd8f7fa112f13a62f71c3:570:17)↵    at exports.check (http://localhost:3000/packages/check.js?hash=bf95dee84c2be9008274d2385c637659760b9057:67:15)↵    at new UploadInstance (http://localhost:3000/packages/ostrio_files.js?hash=ca8aebee86f897f5101171ceb14fd08e066f1bb1:2593:7)↵    at FilesCollection.exports.FilesCollection.FilesCollection.insert (http://localhost:3000/packages/ostrio_files.js?hash=ca8aebee86f897f5101171ceb14fd08e066f1bb1:2551:12)↵    at Blaze.TemplateInstance._insert (http://localhost:3000/packages/yogiben_autoform-file.js?hash=3d363e8d810a0573e329d6dd6afecd4518e0db13:244:23)↵    at Object.fileuploadchange .js-file (http://localhost:3000/packages/yogiben_autoform-file.js?hash=3d363e8d810a0573e329d6dd6afecd4518e0db13:345:14)↵    at http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:3718:20↵    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:3687:12)↵    at Blaze.View.<anonymous> (http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:3717:25)"__proto__: Errorstack: "Error↵    at exports.check (http://localhost:3000/packages/check.js?hash=bf95dee84c2be9008274d2385c637659760b9057:67:15)↵    at new UploadInstance (http://localhost:3000/packages/ostrio_files.js?hash=ca8aebee86f897f5101171ceb14fd08e066f1bb1:2593:7)↵    at FilesCollection.exports.FilesCollection.FilesCollection.insert (http://localhost:3000/packages/ostrio_files.js?hash=ca8aebee86f897f5101171ceb14fd08e066f1bb1:2551:12)↵    at Blaze.TemplateInstance._insert (http://localhost:3000/packages/yogiben_autoform-file.js?hash=3d363e8d810a0573e329d6dd6afecd4518e0db13:244:23)↵    at Object.fileuploadchange .js-file (http://localhost:3000/packages/yogiben_autoform-file.js?hash=3d363e8d810a0573e329d6dd6afecd4518e0db13:345:14)↵    at http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:3718:20↵    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:3687:12)↵    at Blaze.View.<anonymous> (http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:3717:25)↵    at http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:2560:30↵    at Object.Blaze._withCurrentView (http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:2214:12)"__proto__: Error
exports.check @ match.js:39
UploadInstance @ ostrio_files.js?hash=ca8aebe…:2593
exports.FilesCollection.FilesCollection.insert @ ostrio_files.js?hash=ca8aebe…:2551
_insert @ autoform-file.coffee:36
fileuploadchange .js-file @ autoform-file.coffee:101
(anonymous) @ template.js:496
Template._withTemplateInstanceFunc @ template.js:465
(anonymous) @ template.js:495
(anonymous) @ view.js:884
Blaze._withCurrentView @ view.js:538
(anonymous) @ view.js:883
(anonymous) @ events.js:47
dispatch @ jquery.js:4665
elemData.handle @ jquery.js:4333
trigger @ jquery.js:4574
(anonymous) @ jquery.js:5284
each @ jquery.js:384
each @ jquery.js:136
trigger @ jquery.js:5283
_trigger @ mpowaga_jquery-ui-widget.js:533
(anonymous) @ mpowaga_jquery-fileupload.js:1238
fire @ jquery.js:3143
add @ jquery.js:3189
always @ jquery.js:3290
_onChange @ mpowaga_jquery-fileupload.js:1233
(anonymous) @ mpowaga_jquery-ui-widget.js:135
handlerProxy @ mpowaga_jquery-ui-widget.js:446
dispatch @ jquery.js:4665
elemData.handle @ jquery.js:4333
```

**Comment by dr-dimitru** [comment]
Hi @kenshinman ,

Sorry for delay. Working on next release. Can't reproduce this issue on my end.
What OS and Browser you're using?

**Comment by dr-dimitru** [comment]
Hi @kenshinman ,

Have you tried latest release?
Is issue still persists on your end?

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
