### ISSUE TITLE
Can´t find collection if not directly in global scope

### ISSUE THREAD

**Issue by Mklueh** [VeliovGroup/meteor-autoform-file#19]
I´ve encapsulated my collections in a Collections = {} object, but your lib is looking for it directly in the global scope.

`var upload = global[template.collectionName()].insert({
......`

I actually don´t know if it´s possible in general to find a solution for it, but I thought I´ve mention it if others having the same problem.

As a workaround I´ve solved it by setting the collection to the global scope manually

```
import Collections from '/collections';

if (Meteor.isClient) {

    Template.your_template.onRendered(function () {
        global[Collections.YourImageCollection.collectionName] = Collections.YourImageCollection;
    })

}
```

**Comment by dr-dimitru** [comment]
Hello @Mklueh ,
Thank you for this tip.

**Comment by thebarty** [comment]
I LOVE IT!! Thanks for the tip!

**Comment by jankapunkt** [comment]
Just as a side question - Why don't you use dburles:mongo-collection-instances to get the collection? Does it not support those FileSystem collection instances? Would it make sense to have them included in dburles:mongo-collection-instances?

**Comment by jankapunkt** [comment]
Added a backward compatible PR which makes use of dburles:mongo-collection-instances : #28

**Comment by dr-dimitru** [comment]
Can be fixed by using `dburles:mongo-collection-instances`, since [`v2.0.2`](https://github.com/VeliovGroup/meteor-autoform-file/releases/tag/2.0.2)

**Comment by dr-dimitru** [comment]
Feel free to reopen it in case if the issue still persists on your end.
