### ISSUE TITLE
File remove only works on browser console

### ISSUE THREAD

**Issue by rikyperdana** [VeliovGroup/meteor-autoform-file#20]
Clicking 'Remove' link on form only remove the record from collection, but not the file
But when I execute Images.remove({_id: 'RYQR6Zn3Mypgkpnkd'}) the file on upload folder removed
What did I do wrong?

**Comment by rikyperdana** [comment]
I'm sorry, it solved by setting allowClientCode: true

**Comment by dr-dimitru** [comment]
I'm glad you have solved it

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/meteor-autoform-file)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/autoform-files)
