### ISSUE TITLE
autoform dependency to 6.0.0

### ISSUE THREAD

**Issue by s1rd4v3** [VeliovGroup/meteor-autoform-file#22]
could you please update and test your package to work with the newely released autoform 6.0.0 package?

thanks a lot for you work!

**Comment by dr-dimitru** [comment]
Hi @s1rd4v3 ,

It is coming - https://github.com/VeliovGroup/meteor-autoform-file/pull/21

**Comment by s1rd4v3** [comment]
@dr-dimitru cool. Thanks for the update!

**Comment by costezki** [comment]
Any news on this issue?

**Comment by dr-dimitru** [comment]
Hello @costezki ,

If you're familiar with AF internal. I'll be glad if you point us to the fix of this issue (I've requested changes on #21 , but without response from @Buom01):

> [this line](https://github.com/VeliovGroup/meteor-autoform-file/pull/21/files/8a9d7dba7dc51bf6ff77bae8c81914ee4f16e0a1#diff-a121918b7a11d33026d42199c22453e3R78) now throws:
> 
> ```
> Uncaught TypeError: Cannot read property 'addInvalidKeys' of undefined
> ```
> 
> So, `AutoForm.getValidationContext()` returns `undefined`.


Any ideas will be helpful.

**Comment by dr-dimitru** [comment]
Done in [v2.0.1](https://github.com/VeliovGroup/meteor-autoform-file/releases/tag/2.0.1)
Feel free to reopen it in case if the issue still persists on your end.
