### ISSUE TITLE
Project Build gives SyntaxError: Unexpected token: punc ())

### ISSUE THREAD

**Issue by i-siddiq** [VeliovGroup/meteor-autoform-file#23]
Hi, 
I am using **Meteor@1.4.3.1, ostrio:files@1.7.12, ostrio:autoform-files@1.0.12, aldeed:autoform@5.8.1, aldeed:collection2@2.10.0**. Browser **chrome** and **macOS Sierra v 10.12.1.**

My project is **working fine** but when I try to build it the following error occurs.

> Errors prevented bundling:                    
While minifying app code:                     
packages/minifyStdJS_plugin.js:113:28: UglifyJS minification error: 

>SyntaxError: Unexpected token: punc ()) at packages/ostrio_autoform-files/lib/client/fileUpload.js line 16

>within packages/ostrio_autoform-files.js (line: 195, col: 25, pos: 18455):

>this.collectionName = () => {

>at maybeThrowMinifyErrorBySourceFile (packages/minifyStdJS_plugin.js:113:28)
at packages/minifyStdJS_plugin.js:145:9
at Array.forEach (native)
at UglifyJSMinifier.processFilesForBundle (packages/minifyStdJS_plugin.js:130:9)

My relevant code is as follows:
_images.js_

``` javascript


this.Images = new FilesCollection({
  debug: true,
  collectionName: 'Images',
  allowClientCode: true, // Disallow remove files from Client,
  onbeforeunloadMessage: function () {
  return 'Upload is still in progress! Upload will be aborted if you leave this page!';
  },

  onBeforeUpload: function (file) {
    // Allow upload files under 10MB, and only in png/jpg/jpeg formats
    if (file.size <= 10485760 && /png|jpg|jpeg|mp4/i.test(file.ext)) {
      return true;
    } else {
      return 'Please upload image/video(png,jpg,jpeg,mp4 only), with size equal or less than 10MB';
    }
  }

});


if (Meteor.isClient) {
  Meteor.subscribe('files.images.all');
}

if (Meteor.isServer) {
  Meteor.publish('files.images.all', function () {
    return Images.find().cursor;
  });
  Images.allow({
    insert: function() {
      return true;
    },
    update: function() {
      return true;
    },
    remove: function() {
      return true;
    }
  });
}

```

**Comment by jlourenco** [comment]
+1

**Comment by dr-dimitru** [comment]
Hello @i-siddiq n @jlourenco ,

This is known Meteor issue, please see - https://github.com/meteor/meteor/issues/8020

In short - it can be solved by using `abernix:standard-minifier-js` package
```shell
meteor remove standard-minifier-js
meteor add abernix:standard-minifier-js
```

Hope this will help, let me know

**Comment by jlourenco** [comment]
Hi @dr-dimitru 
Thanks, that solved it!

**Comment by i-siddiq** [comment]
Hi @dr-dimitru , I did as you recommended but this time I get a similar error, could you please check it. Thanks. I have **abernix:minifier-js @1.3.17** and **abernix:standard-minifier-js@1.3.3** installed.
```
Errors prevented bundling:                    
While minifying app code:                     
packages/minifyStdJS_plugin.js:72:28: UglifyJS minification error: 

SyntaxError: Unexpected token: name (package) at packages/iron_core/lib/iron_core.js line 257

within packages/iron_core.js (line: 323, col: 29, pos: 29580):

Iron.utils.debug = function (package) {                                                         

at maybeThrowMinifyErrorBySourceFile (packages/minifyStdJS_plugin.js:72:28)
at packages/minifyStdJS_plugin.js:103:9
at Array.forEach (native)
at UglifyJSMinifier.processFilesForBundle (packages/minifyStdJS_plugin.js:89:9)
```

**Comment by dr-dimitru** [comment]
Hello @i-siddiq ,

Looks like issue is in `iron_core` package, and it's old and [stale package](https://github.com/iron-meteor/iron-core/blob/master/package.js#L9) - I'll assume it's not compatible with latest meteor.

First what you can do is make sure `ecmascript` package is installed into your app and it's above all non-meteor packages in `.meteor/packages` file

**Comment by i-siddiq** [comment]
@dr-dimitru I tried every thing and nothing worked. I had to go change the source code of `iron_core` package. The problem is that there are reserved key words in ES6 where some are reserved for future purposes, these can be used in some situations so runtime does not give error. I think UglifyJS is strict and does not allow future reserved keywords too hence the discrepancy.

**Comment by dr-dimitru** [comment]
@i-siddiq agree, easiest way is to fork IR, and probably send a PR
