### ISSUE TITLE
Exception in template helper

### ISSUE THREAD

**Issue by Saydn** [VeliovGroup/meteor-autoform-file#25]
Hi,

I hope this is the right place for this and I'm sure the problem is with me and a mistake I've made or something I've misunderstood but I've been trying to figure it out for ages and I don't know what to try honestly. 

After I upload a photo and submit the form I get the error message "Photo is required" even though there is a photo. I tried setting the field to `optional: true` and the form then submitted but I've no idea where the image went or how to find and use it.

Sorry, I'm sure this is a trivial problem and it's my lack of understanding but I really appreciate your help.

Thanks!

**Comment by dr-dimitru** [comment]
Hello @Saydn ,

Could you post some of your code. please (related to file-upload of course)?

**Comment by Saydn** [comment]
@dr-dimitru 

Here is the code I have pertaining to the image upload :)

Image Schema:
`var Images = new FilesCollection({
	collectionName: 'Images',
	allowClientCode: true, // Required to let you remove uploaded file
	onBeforeUpload: function (file) {
		// Allow upload files under 10MB, and only in png/jpg/jpeg formats
		if (file.size <= 10485760 && /png|jpg|jpeg/i.test(file.ext)) {
			console.log("success!!!");
			return true;
		} else {
			return 'Please upload image, with size equal or less than 10MB';
		}
	}
})`

Recipe Schema(in part) which drives the autoform:
`RecipeSchema = new SimpleSchema({
	photo: {
		type: String,
		autoform: {
			afFieldInput: {
				type: 'fileUpload',
				collection: 'Images',
/*
				uploadTemplate: 'uploadField', // <- Optional
				previewTemplate: 'uploadPreview' // <- Optional
*/
			}
		}
	},
	name: {
		type: String,
		label: "Name",
	},
	desc: {
		type: String,
		label: "Description",
		optional: true,
	},...`

In server/publish.js:
`Meteor.publish('files.images.all', function () {
	return Images.collection.find({});
});`

In my recipe create js:
`Meteor.subscribe('files.images.all');`

In the recipe create page html:
`{{> quickForm collection="Recipes" id="createRecipe" type="insert"}}`

Everything in the schema, collection and form seems to work as expected otherwise :)

Thanks for your help!

**Comment by dr-dimitru** [comment]
In the first example
```js
var Images
```
Should be exposed to global namespace, to do so omit `var` keyword or do:
```js
this.Images = /* ... */
```

**Comment by Saydn** [comment]
@dr-dimitru Perfect! The error isn't appearing any more. Thanks so much.

While I have you here, how would I reference the image now to use it or where would I find it to check it has uploaded okay?

**Comment by dr-dimitru** [comment]
Great 👍 

 - By default files goes to: `yourProdAppDir/.meteor/local/build/programs/server/assets/app/uploads`, for more info read [FAQ](https://github.com/VeliovGroup/Meteor-Files#faq)
 - Alter default behavior with `storagePath` option

To check files, go to `storagePath` and check them :)

To display files see [Template-Helper docs](https://github.com/VeliovGroup/Meteor-Files/wiki/Template-Helper)

Let me know if it helps

**Comment by Saydn** [comment]
@dr-dimitru Thanks so much for your help.

I've follow the instructions on the Template-Helper docs but it doesn't seem to be retrieving the files at all. I've checked and the images are definitely uploading correctly.

This is my Schema, publish and subscription. I lift the subscription as global to meteor as I seem to remember reading that it needs to be that way. I tried both 'files.images.all' and 'files.all' but it didn't seem to make a difference.
```
Images = new FilesCollection({
	collectionName: 'Images',
	allowClientCode: true, // Required to let you remove uploaded file
	onBeforeUpload: function (file) {
		// Allow upload files under 10MB, and only in png/jpg/jpeg formats
		if (file.size <= 10485760 && /png|jpg|jpeg/i.test(file.ext)) {
			return true;
		} else {
			return 'Please upload image, with size equal or less than 10MB';
		}
	}
})

if (Meteor.isClient) {
	Meteor.subscribe('files.images.all');

	Template.View.helpers({
		fileRef: Images.collection.findOne({})
	})

} else {

	Meteor.publish('files.images.all', function () {
		return Images.collection.find({});
	});
}
```

This is the template file:
```
<template name="View">
	<article class="recipe">

		<img src="{{fileURL fileRef 'thumb'}}" alt="{{fileRef.name}}" />
		<br>
		
		<a href="{{fileURL fileRef}}?download=true" target="_parent" download="{{fileRef.name}}">
		  link: {{fileRef.name}}
		</a>
		
		<br>
		{{#if fileRef}}
			success
		{{else}}
			fail
		{{/if}}...
```

None of the things referencing the image in the template display anything.

Thanks again for your help!

**Comment by dr-dimitru** [comment]
Hello @Saydn ,

Enable "debug" mode to see data flow, via `Images = new FilesCollection({debug: true /*...*/});`

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
