### ISSUE TITLE
Syntax error in older browser + Phantom.js + Prerender.io

### ISSUE THREAD

**Issue by derouck** [VeliovGroup/meteor-autoform-file#26]
The latest version causes a syntax error bug. It also prerendering on prerender.io and probably with spiderable as well.

I had it on the 1.3.5.1 and now on 1.4.4.1 the issue is still present. I was on abernix:standard-minifier-js but moved to latest standard-minifier-js@2.0.0

For me the problem is solved by going back one release 1.0.11. I could reproduce the bug easily in version 19 of firefox. I was mostly interested in fixing the prerender issues and just needed an old enough browser. I don't know how many browser version are affected.

But if anyone encounters the same, you can fix it by locking to the older version.

**Comment by dr-dimitru** [comment]
Hello @derouck ,

I know it's kind of late, but this should be fixed in [v2.0.1](https://github.com/VeliovGroup/meteor-autoform-file/releases/tag/2.0.1)

Feel free to reopen it in case if the issue still persists on your end.
