### ISSUE TITLE
Uncaught TypeError: zeroBuffer.fill is not a function

### ISSUE THREAD

**Issue by marcoschwartz** [VeliovGroup/meteor-autoform-file#27]
Hello,

Thanks for the recent update of this package! However, when I try to use it in my app, I get the following error on the client and see the iron-router error page:

> Uncaught TypeError: zeroBuffer.fill is not a function

The only way to get rid of this is to remove the package. I followed the example from the Readme, however I am using the S3 integration so I have my Files collection in the import folder and I import it using:

`import Files from '../imports/api/files';`

Could that be the source of the problem? Thanks!

**Comment by dr-dimitru** [comment]
Hello @marcoschwartz ,

It's caused by:
 - Meteor@1.5.* removed `Buffer` polyfill
 - SimpleSchema (wich is dependency of Autoform) expects to have `Buffer` in global scope

See solution in Benjamn's answer [here](https://github.com/meteor/meteor/issues/8645#issuecomment-298349964)

Let me know if it helps

**Comment by marcoschwartz** [comment]
Hello,

Unfortunately I still have the issue while doing this, I actually already had:

`global.Buffer = global.Buffer || require("buffer").Buffer;`

Inside lib/init.js on the client. Do you have other ideas to fix the issue? Thanks!

**Comment by marcoschwartz** [comment]
Maybe the whole output would help:

> printer.js:170 Uncaught TypeError: zeroBuffer.fill is not a function
    at helpers.js (printer.js:170)
    at fileEvaluate (modules-runtime.js?hash=8587d18…:343)
    at require (modules-runtime.js?hash=8587d18…:238)
    at md5.js (printer.js:170)
    at fileEvaluate (modules-runtime.js?hash=8587d18…:343)
    at require (modules-runtime.js?hash=8587d18…:238)
    at browser.js (printer.js:170)
    at fileEvaluate (modules-runtime.js?hash=8587d18…:343)
    at require (modules-runtime.js?hash=8587d18…:238)
    at index.js (printer.js:170)

**Comment by dr-dimitru** [comment]
@marcoschwartz ,

 1. Is it Server or Client?
 2. How SimpleSchema is installed at your end? (NOTE: only [NPM version](https://github.com/aldeed/node-simple-schema) uis guaranteed to work)
 3. What Autoform version is installed in your app?

**Comment by marcoschwartz** [comment]
1. The error is on the client side
2. SimpleSchema is installed via NPM, version 0.3.1
3. Autoform is 6.2.0

**Comment by dr-dimitru** [comment]
1. Does the stacktrace points to some exact file or library? (*Can't figure out where it may came from*)
 2. Could we have minimal reproduction app?

**Comment by marcoschwartz** [comment]
1. Apparently it's coming from printer.js, at the function:

`PrintVisitor.prototype.HashPair = function(pair) {
  return pair.key + '=' + this.accept(pair.value);
};
/* eslint-enable new-cap */
`

However I don't know how to see what is calling this file

2. Actually I tried the module in another application, and it works fine! So probably it's a conflict with another module. How could I see which Meteor package or node module is causing the problem?

**Comment by dr-dimitru** [comment]
> Actually I tried the module in another application, and it works fine!

Phew.... That's the good news.

> How could I see which Meteor package or node module is causing the problem?

Let's start with stacktrace (the error) screenshot. As when you copy-paste it looses some info

**Comment by marcoschwartz** [comment]
Sure, here it is:

<img width="1290" alt="screen shot 2017-07-23 at 21 06 00" src="https://user-images.githubusercontent.com/1475795/28502087-0355e94c-6feb-11e7-9dba-504c2030d68a.png">

The thing is that in the other application it also shows the error, but it doesn't crash iron-router like in my app, I have this error for all routes:

<img width="917" alt="screen shot 2017-07-23 at 21 05 48" src="https://user-images.githubusercontent.com/1475795/28502085-f864d53e-6fea-11e7-9757-06d17c4bbabf.png">

When I remove this package, iron-router doesn't complain anymore. Note that in both app I have iron-router installed

**Comment by dr-dimitru** [comment]
1. Iron Router complaining as it was loaded but routes wan't defined due to exception (so, script was interrupted), the difference in two apps behavior may be caused by the order of the packages in `.meteor/packages`
 2. Well... error doesn't says much. Click on the `printer.js:170` and try to figure out what is the package it's coming from. You should be able browse packages in a sources tree (dev tools)

**Comment by marcoschwartz** [comment]
That's what I see when I click on it, is there any information there?

<img width="1186" alt="screen shot 2017-07-23 at 21 15 56" src="https://user-images.githubusercontent.com/1475795/28502144-2f0ff98c-6fec-11e7-8ed4-8b4acdca4045.png">

**Comment by dr-dimitru** [comment]
Handlebars?

**Comment by dr-dimitru** [comment]
I'll start commenting packages in `.meteor/packages` to find out which causes an issue. And make sure all packages is up to date

**Comment by marcoschwartz** [comment]
Hello,

OK, after spending most of the night trying to isolate the issue, I found that it comes from the S3 integration somehow. Whenever I put this on the client:

`import Images from '/imports/api/files';`

I get the error. I am using the exact copy & paste from the example. Without the autoform package it works fine. Do you know what could cause this?

**Comment by marcoschwartz** [comment]
Actually now can't even get it working without the S3 integration ... I got:

`Exception from sub files.images.all id emE46pTDeCZAQ2cfk ReferenceError: Images is not defined`

I placed the right subscribe on the client, the publication on the server and the shared code in lib, just as shown in the example ... what I am doing wrong?

**Comment by dr-dimitru** [comment]
Have you imported or initialized `Images` collection in the file where publication is defined??

**Comment by marcoschwartz** [comment]
Ok, I tried to carefully replicate your simples-upload example on this repository:

https://github.com/VeliovGroup/Meteor-Files-Demos

Now the server-side error is gone, but on the client in autoform I still have the error:

> Exception in template helper: TypeError: Cannot read property 'findOne' of undefined
    at Object.uploadedFile (http://localhost:3000/packages/ostrio_autoform-files.js?hash=1dd1917cfe2ae4d6e421f35b0b11ba653ede9004:254:56)
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3051:16
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1715:16
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3103:66
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3744:12)
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3102:27
    at Object.Spacebars.call (http://localhost:3000/packages/spacebars.js?hash=ebf9381e7fc625d41acb0df14995b7614360858a:172:18)
    at http://localhost:3000/packages/ostrio_autoform-files.js?hash=1dd1917cfe2ae4d6e421f35b0b11ba653ede9004:99:22
    at Blaze.View.<anonymous> (http://localhost:3000/packages/spacebars.js?hash=ebf9381e7fc625d41acb0df14995b7614360858a:264:18)
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1934:20

I think I am still missing something ... maybe related to this:

Note: Images variable must be attached to Global scope. And has same name (case-sensitive) as collectionName option passed into FilesCollectio#insert({collectionName: 'Images'}) method, Images in our case.

Thanks for all the help!

**Comment by dr-dimitru** [comment]
Yes, `Images` should be in global scope.
When you define collection:
```js
const Images = new FilesCollection({/* ... */});

// All below should have same result (pick one)
global.Images = Images;
window.Images = Images;
this.Images = Images;
```

**Comment by marcoschwartz** [comment]
That worked, thanks! However, even with this still no luck with the S3 integration, it still returns the same error.

**Comment by marcoschwartz** [comment]
I think I made progress, it's coming from this line in the S3 example:

`import S3 from 'aw-sdk/clients/s3';`

Whenever I add this to my app it make the error I describe above.

**Comment by dr-dimitru** [comment]
Make sure `s3` imported only on the Server

**Comment by marcoschwartz** [comment]
So I should also put all the S3 example in Meteor.isServer inside your simplest-upload example? I am sorry about all the questions but I am really confused, I think an official S3 integration example would be great because now I really don't see where to put the code and adapt your example so everything is at the right place.

**Comment by dr-dimitru** [comment]
Yes, `Meteor.isServer` will work with `require()`.
If you want to use exact code splitting, place server code under `/imports/server/` directory.
Then import needed files.

**Comment by marcoschwartz** [comment]
Ok ... what I did now is to put the exact S3 example in /imports/server, and my image.collection.js (in lib like in your example) is this:

`import Images from '/imports/server/files';

global.Images = Images;

if (Meteor.isServer) {

    Meteor.publish('files.images.all', function() {
        return Images.find().cursor;
    });

} else {
    Meteor.subscribe('files.images.all');
}

export default Images;`

Now I got a new error on client: Uncaught Error: Cannot find module '/imports/server/files'

**Comment by dr-dimitru** [comment]
> Now I got a new error on client: Uncaught Error: Cannot find module '/imports/server/files'

This should probably throw same error on Server too, as `import` needs to be pointed to a file, like `/imports/server/files.js`

And do not import it on the Client, as you can not import files under `/server/` directory on the Client, for conditional imports use `require()`

**Comment by dr-dimitru** [comment]
I'm off for today, I'll be back in 10 hours

**Comment by dr-dimitru** [comment]
@marcoschwartz have you solved it?

**Comment by marcoschwartz** [comment]
Yeah that works now, thanks for the help! However I somehow needed to put all the code for the S3 integrations into a single file, so it's a bit more messy now but it works :) Closing this

**Comment by Roshdy** [comment]
@marcoschwartz  Can you please post a sample code and file structure how you managed to make it work?

**Comment by marcoschwartz** [comment]
Sure thing, I am attaching the file that I placed in the /lib folder. Then I just import this file using:

`import Images from '/lib/images.collection.js';`

[images.collection.js.zip](https://github.com/VeliovGroup/meteor-autoform-file/files/1220384/images.collection.js.zip)

**Comment by Aparus** [comment]
I have exactly the same issue. And nothing from  here did help me (

**Comment by Aparus** [comment]
@marcoschwartz thank you so much! I was 2 days working with it , before met your answer )) 
do you know , that all code in /lib folder works without "import" ?
