### ISSUE TITLE
After saving file Remove button doesn't work more

### ISSUE THREAD

**Issue by Aparus** [VeliovGroup/meteor-autoform-file#29]
![image](https://user-images.githubusercontent.com/1222611/29456936-895796f0-8420-11e7-922b-1bb9c61c0f02.png)
Before first save remove button works, but after save it doesn't. 
At first I was using package without Amazon s3 integration, now with it. Both variant the same.

**Comment by dr-dimitru** [comment]
Hello @Aparus ,

 1. Do you have any Client or Server errors/logs?
 2. Could you please post how you initiate *FilesCollection*?
 3. Enable "debug" mode in [*Constructor*](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor) and post full logs from Server and Client

**Comment by felixhamel** [comment]
I have the exact same problem. Here's the debug logs

```
[FilesCollection] [FileCursor] [remove()] client.coffee:42 
[FilesCollection] [remove("3Qw6Pkfk5ZsBDLXux")] client.coffee:42 
[FilesCollection] [remove] Run code from client is not allowed! client.coffee:42 
```

It started this morning or yesterday. I don't remember to have changed anything since.

**Comment by dr-dimitru** [comment]
Hello @felixhamel ,

Well this warning is expressive:
```
Run code from client is not allowed!
```

To solve this set `config.allowClientCode` to `true` in a [*FilesCollection* Constructor](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor).

For security reasons I highly recommend to define rules in a `onBeforeRemove`, see [`.remove()` docs](https://github.com/VeliovGroup/Meteor-Files/wiki/remove)

**Comment by felixhamel** [comment]
Hi @dr-dimitru,

I found the solution at the same you replied to me. Yes I'll make sure that just the right people will be able to remove files.

Thanks!

**Comment by Aparus** [comment]
In console there is no errors, both, on server and client. I use ostrio:autoform-files@2.0.2

**Comment by Aparus** [comment]
@dr-dimitru thanks, I've solved it.. now another problem. after a while files disapears from localhost and on heroku server. I did I hope everything in instruction about Amazon S3 integration, but still the same problem.. But I will ask about it in another place.

**Comment by dr-dimitru** [comment]
@Aparus okay. Feel free to ask at the [main rep](https://github.com/VeliovGroup/Meteor-Files/issues)

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
