### ISSUE TITLE
Setting default upload protocol?

### ISSUE THREAD

**Issue by marcoschwartz** [VeliovGroup/meteor-autoform-file#30]
Hello,

We noticed some issues when uploading big files with this package, and I know we fixed this in the past (before using autoform) by switching from DDP for upload to HTTP. 

So I wondered what is the default protocol used by this package? Is it possible to change it somewhere? Thanks!

**Comment by dr-dimitru** [comment]
Hello @marcoschwartz ,

Default transport is `ddp`, as stated here: https://github.com/VeliovGroup/Meteor-Files/blob/master/docs/insert.md

> So I wondered what is the default protocol used by this package? Is it possible to change it somewhere?

No, at least not now.

Should I consider this as feature request?

**Comment by marcoschwartz** [comment]
Thanks for the explanation! Indeed, it would be great to have this option :)

**Comment by dr-dimitru** [comment]
Hello @marcoschwartz ,

Thank you a lot for this contribution.
Please see [`v2.0.4`](https://github.com/VeliovGroup/meteor-autoform-file/releases/tag/2.0.4), let me know how it work on your end

**Comment by marcoschwartz** [comment]
Hello, you're welcome, can't wait to try it out! So what should I do exactly so my app uses HTTP for all file uploads?

**Comment by dr-dimitru** [comment]
@marcoschwartz two options:
 - [Define in schema](https://github.com/VeliovGroup/files-gridfs-autoform-example/blob/master/lib/persons.js#L36)
 - [Define in `afQuickField` as attribute](https://github.com/VeliovGroup/files-gridfs-autoform-example/blob/master/client/newPerson.html#L4)

Let me know how it work on your end

**Comment by marcoschwartz** [comment]
Great, thanks! I just had a quick test on one of my schema, it works well!

**Comment by dr-dimitru** [comment]
I'm glad it's working for you.
Closing.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
