### ISSUE TITLE
rewrite fileUpload template

### ISSUE THREAD

**Issue by Aparus** [VeliovGroup/meteor-autoform-file#31]
what should I do with template, for add to it some elemets (like Remove button available only for admin etc)? when I just copy it and rename it fires errors. What should I pass to it and how... 
[fileUpload.html](https://github.com/VeliovGroup/meteor-autoform-file/blob/master/lib/client/fileUpload.html)

**Comment by dr-dimitru** [comment]
As stated in the [docs](https://github.com/VeliovGroup/meteor-autoform-file#custom-file-preview), you have to set name of the custom template to `previewTemplate` of defined `afFieldInput` rule:
```js
picture: {
  type: String,
  autoform: {
    afFieldInput: {
      type: 'fileUpload',
      collection: 'Images',
      previewTemplate: 'myFilePreview'
    }
  }
}
```

You should be good with next markup:
```spacebars
<template name="myFilePreview">
      <span>{{name}}</span>
      <a data-remove-file href="#">Remove</a>
</template>
```

>  when I just copy it and rename it fires errors.

What errors exactly?

**Comment by Aparus** [comment]
For just a test I've copied whole fileUpload.html to my file "ArticleUpdate.html" (which contains my autoForm), and renamed it to myFileUpload. 
```js
<template name="myFileUpload">
  <input value="{{fileId}}" type="hidden" {{this.atts}}>
  {{#with uploadedFile}}
    {{#if previewTemplate}}
      {{>Template.dynamic template=previewTemplate}}
    {{else}}
      <div>
        {{#if isImage}}
          {{> uploadImageDemo}}
        {{else}}
          {{> uploadFileDemo}}
        {{/if}}
      </div>
      <a data-reset-file href="#" style="display:none">Reset</a>
      <a data-remove-file href="#">Remove</a>
    {{/if}}
  {{else}}
    {{#if uploadTemplate}}
      {{>Template.dynamic template=uploadTemplate data=currentUpload}}
    {{else}}
      {{#with currentUpload}}
        Uploading <b>{{file.name}}</b>:
        <progress value="{{progress.get}}" max="100"></progress>
        &nbsp;
        <span class="progress">{{progress.get}}%</span>
      {{else}}
        <input data-files-collection-upload class="form-control af-file-upload-capture" type="file" />
      {{/with}}
    {{/if}}
  {{/with}}
</template>
```
Then this new template name I've added to schema:
```js
    picture: {
        type: String,
        optional: true,
        autoform: {
            afFieldInput: {
                type: 'fileUpload',
                collection: 'Images',
                uploadTemplate: 'myFileUpload'
                }
            }
    },
```
After that when I open page with ArticleUpdate , there are blank page, and errors:
![screenshot from 2017-08-20 07-59-25](https://user-images.githubusercontent.com/1222611/29492229-a302d1e2-857d-11e7-888e-561c06db0b9f.png)
Sorry if the question is too naive. I'm new in meteor and I even couldn't find this template in my project folder. Currently I'm reading about meteor packages to fix my ignorance.

**Comment by dr-dimitru** [comment]
In my previous answer I gave you a template you need to implement your own file preview. No need to copy/paste whole `afFileUpload` - it wouldn't work.

Once again - template:
```html
<template name="myFilePreview">
  <span>{{name}}</span>
  <a data-remove-file href="#">Remove</a>
</template>
```

**Comment by Aparus** [comment]
@dr-dimitru thanks, it solved my issue. 
And one last question, how to allow remove images only to their uploaders? 
I've looked at Image object , there are not fields about creator of file

**Comment by dr-dimitru** [comment]
If Image was uploaded on behalf of logged in user, `userId` should be filled.
Anyways I recommend to place all custom fields, like `ownerId` to `meta` Object.

See [`onBeforeRemove` hook](https://github.com/VeliovGroup/Meteor-Files/wiki/Constructor#use-onbeforeremove-to-avoid-unauthorized-remove) for more info.
Speaking of `meta` Object, currently it's not possible to change it in `ostrio:autoform-files` package, #30 will make it possible to pass custom Object to `.insert()` method

**Comment by Aparus** [comment]
yes, there is userId.  I am Inattentive today (
thank you for support! and sorry for disturbing! :) 
good plugin. helped me so mach.

**Comment by dr-dimitru** [comment]
@Aparus glad to help :)

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
