### ISSUE TITLE
No File upload button

### ISSUE THREAD

**Issue by newb007** [VeliovGroup/meteor-autoform-file#34]
Please forgive my newness to meteor, but I tried the example code and ran into an issue.  The website starts up just fine and I see the title (with corresponding text box) and the Submit button.  I also see the Picture text, but I cannot get the upload button (that goes along with it) to appear.  I am using the very latest meteor 1.5.2 (with all of the required packages).  I also installed meteortoys and I see that the "posts" and "Images" collections are created (but don't fill out since there isn't an upload button).  Is there something else that needs done to get a visible "upload" button, or is something no longer working as intended?  Thank you very much for any assistance.

**Comment by newb007** [comment]
Also, I am using the quickform (like the example shows) if that helps. Thanks again for any assistance.

**Comment by dr-dimitru** [comment]
Hello @newb007 ,

Please update to the latest package release (*which is just released*), as you may ran into #32 

Let me know if update is solved your issue

**Comment by newb007** [comment]
Hi dr.dimitru,

Thank you for your quick response and build update.  I much appreciate
that.  I ran the update.  I still don't have an "upload" button on my
screen that I can use to select a file, but the update did get rid of the
errors mentioned in #32 (and I have no errors now).  Again, there is a
"Title" field that I can type into and a "Submit" button (so it looks like
the quickform is loading), but it the 'fileUpload' button doesn't show up.
I am referencing the autoform from the .html like:

<template name="uploadFiles">
{{> quickForm id="postsInsertForm" collection="Posts" type="insert"}}
</template>

As I am still new to meteor, maybe I am missing something?

Thank you very much again

**Comment by dr-dimitru** [comment]
@newb007 do you have at least something? Could you make a screenshot? Note: there is shouldn't be an "upload" button, there is should be only `<input type="file">` which triggers upload right after file is selected

**Comment by newb007** [comment]
@dr.dimitru

I have attached a screenshot of the website.  I have also attached my
images.collection.js located in app/lib/ and my main.html located in
app/client. These are the only two files of code for now ( I made a fresh
app and discarded the original main.html and main.js. -- all of the
javascript is in the images.collection.js and will be separated out
later).  I also did meteor add:

ostrio:autoform-files, meteor add ostrio:files, npm install
simpl-schema, meteor
add aldeed:collection2-core, meteor npm install --save simpl-schema, meteor
add dburles:mongo-collection-instances, meteor add meteortoys:allthings

This is my entire build to this point (I am trying to keep it just like
your example until I get it to work). Please note that I added "REMOVE" to
the extensions so that they would cause a problem in the attachment.

Thank you very much again! :-)

**Comment by newb007** [comment]
I meant to say "so that they wouldn't cause a problem in the attachment"

Thank you again

**Comment by dr-dimitru** [comment]
@newb007 I'm afraid GitHub does not support email attachments. Please post images directly via github.com

**Comment by newb007** [comment]
[images.collection.js.txt](https://github.com/VeliovGroup/meteor-autoform-file/files/1290261/images.collection.js.txt)
[main.html.txt](https://github.com/VeliovGroup/meteor-autoform-file/files/1290260/main.html.txt)

![simpleuploadform](https://user-images.githubusercontent.com/31810713/30246119-f36d6b20-95ad-11e7-9eca-b0d98daf2d71.png)

**Comment by dr-dimitru** [comment]
Remove those two lines:
```js
        uploadTemplate: 'uploadField', // <- Optional
        previewTemplate: 'uploadPreview' // <- Optional
```

**Comment by newb007** [comment]
Awesome! It works now.  Thank you so much! :-)

**Comment by dr-dimitru** [comment]
I'm glad this one is solved :)

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
