### ISSUE TITLE
only upload on submit 

### ISSUE THREAD

**Issue by Farkal** [VeliovGroup/meteor-autoform-file#38]
Is it possible to only upload the file when the user submit the autoform ? With the actual behavior an user can flood my server by sending a lot of fake files.
I have also another question about using `afFieldInput` to get the button to select the file. When I use it, I can choose my file but nothing happen when I submit my form (no error, just all the field are cleaned).

**Comment by dr-dimitru** [comment]
Hello @Farkal ,

I've mentioned the same [issue here](https://github.com/VeliovGroup/meteor-autoform-file/issues/37#issuecomment-342011360). The current problem is what we're looking for help here, AutoForm API isn't obvious at all, so we need someone who knows its internals well.

**Comment by dr-dimitru** [comment]
Closing in favor of #37
