### ISSUE TITLE
Only last file input works when using array of files.

### ISSUE THREAD

**Issue by Aleuck** [VeliovGroup/meteor-autoform-file#39]
I know it is a not very well supported feature, though the `README.md` is unclear whether what is unsupported is the array method or multi-file from a single `<input>`.

When using autoform's `quickForm` with a schema featuring an array of files, if you click the plus button multiple times to make the amount of file input fields you need before selecting any file, only the last of the fields will work.

Probably unrelated, but I couldn't do the schema exactly as described by the example on `README.md`:
```javascript
// ...
  pictures: {
    type: [String],
    label: 'Choose file' # optional
  },
  "pictures.$": {
    autoform: {
      afFieldInput: {
// ...
```
It gave me an error:
`Error: Invalid definition for pictures field: "type" may not be an array. Change it to Array.`
So I had to change the schema definition as follow:
```javascript
/* ... */
  pictures: {
    type: Array, // changed this
    label: 'Choose file' # optional
  },
  "pictures.$": {
    type: String,  // added this
    autoform: {
      afFieldInput: {
/* ... */
```

**Comment by MohammedEssehemy** [comment]
for the schema 
starting from aldeed:autoform 6+ it uses [simpl-schema npm package](https://github.com/aldeed/simple-schema-js) instead of [meteor-simple-schema](https://github.com/aldeed/meteor-simple-schema)
check the [CHANGELOG](https://github.com/aldeed/meteor-autoform/blob/devel/CHANGELOG.md#600)
 and so the second schema definition is the correct one
we need to update the docs

**Comment by MohammedEssehemy** [comment]
I managed to work around the problem using the following approach:
1- hide the remove link from uploaded file preview
2- attach file actions with autoform action 
`  // remove file when clicking array remove btn
  $('.autoform-remove-item-wrap').on('click', function() {
    $('[data-remove-file]').first().trigger('click');
  });
  // prevent user from adding multiple empty uploaders
  $('.autoform-add-item').on('click', function(e) {
    let array_items = AutoForm.getFieldValue('files', 'insertDocForm');
    let available_slots = $('.autoform-array-item').size();
    if (array_items && available_slots > array_items.length) {
      e.stopPropagation();
    }
  });`

**Comment by dr-dimitru** [comment]
Hello @MohammedEssehemy ,

Thank you for this research.

> we need to update the docs

Do you wish to send a PR?

> 1- hide the remove link from uploaded file preview
> 2- attach file actions with autoform action

Does it requires us to update the codebase? Or this is up to the individual implementation?

**Comment by MohammedEssehemy** [comment]
Hello @dr-dimitru 

> Do you wish to send a PR? 

I'll send one this week.

> Does it requires us to update the codebase? Or this is up to the individual implementation?

I think the codebase will need enhancement since the default behaviour (having remove button for removing files and another  button for removing array element) is ambiguous and doesn't provide good UX.

**Comment by dr-dimitru** [comment]
@MohammedEssehemy sounds good, thank you. Looking forward your PR.
