### ISSUE TITLE
Getting an error with the published version

### ISSUE THREAD

**Issue by benjick** [VeliovGroup/meteor-autoform-file#5]
```
Exception in template helper: TypeError: Cannot read property 'find' of undefined
    at Object.uploadedFile (http://localhost:3000/packages/ostrio_autoform-files.js?hash=e71cbd4cce6282f7012a072add14293ffd54f877:138:60)
    at http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:2994:16
    at http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:1653:16
    at http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:3046:66
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:3687:12)
    at http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:3045:27
    at Object.Spacebars.dot (http://localhost:3000/packages/spacebars.js?hash=65db8b6a8e3fca189b416de702967b1cb83d57d5:234:13)
    at http://localhost:3000/packages/ostrio_autoform-files.js?hash=e71cbd4cce6282f7012a072add14293ffd54f877:72:65
    at .<anonymous> (http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:2677:44)
    at http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:1875:20
```

My code: 

```js
import { FilesCollection } from 'meteor/ostrio:files';

const Images = new FilesCollection({
  collectionName: 'Images',
  allowClientCode: false, // Disallow remove files from Client,
  onBeforeUpload(file) {
    // Allow upload files under 10MB, and only in png/jpg/jpeg formats
    if (file.size <= 10485760 && /png|jpg|jpeg/i.test(file.ext)) {
      return true;
    }
    return 'Please upload image, with size equal or less than 10MB';
  },
});

export default Images;
```

and then in the schema

```js
picture: {
  type: String,
  autoform: {
    afFieldInput: {
      type: 'fileUpload',
      collection: 'Images',
    },
  },
},
```

**Comment by dr-dimitru** [comment]
Hi @benjick 
 - Which version of FilesCollection are you using?
 - Which version of Meteor?

**Comment by dr-dimitru** [comment]
And most important quesion: *Is* `Images` *available in global scope?*

**Comment by benjick** [comment]
Hey

I'm using `METEOR@1.4.0.1` and `ostrio:files@1.6.9`.

I'm not sure with on the global scope, but if I don't put `const` in from of `Images = new FilesCollection({` I get this error:

```
Error: No such function: $gt
    at lookup.js:191
    at Spacebars.call (spacebars-runtime.js:136)
    at Spacebars.mustacheImpl (spacebars-runtime.js:70)
    at Object.Spacebars.dataMustache (spacebars-runtime.js:102)
    at template.fileUpload.js:13
    at .<anonymous> (builtins.js:83)
    at view.js:199
    at Function.Template._withTemplateInstanceFunc (template.js:465)
    at view.js:197
    at Object.Blaze._withCurrentView (view.js:538)
```

**Comment by dr-dimitru** [comment]
Change to:
```jsx
import { FilesCollection } from 'meteor/ostrio:files';

this.Images = new FilesCollection({
  collectionName: 'Images',
  allowClientCode: false, // Disallow remove files from Client,
  onBeforeUpload(file) {
    // Allow upload files under 10MB, and only in png/jpg/jpeg formats
    if (file.size <= 10485760 && /png|jpg|jpeg/i.test(file.ext)) {
      return true;
    }
    return 'Please upload image, with size equal or less than 10MB';
  },
});

export default Images;
```

**Comment by dr-dimitru** [comment]
Hold on. Ignore my previous comment.
There is a bug

**Comment by benjick** [comment]
What I would want is something like this (but I don't know if it good enough)

Images.js:
```
import { FilesCollection } from 'meteor/ostrio:files';

const Images = new FilesCollection({
  collectionName: 'Images',
  allowClientCode: false, // Disallow remove files from Client,
  onBeforeUpload(file) {
    // Allow upload files under 10MB, and only in png/jpg/jpeg formats
    if (file.size <= 10485760 && /png|jpg|jpeg/i.test(file.ext)) {
      return true;
    }
    return 'Please upload image, with size equal or less than 10MB';
  },
});

export default Images;
```

MySchema.js
```js
import Images from './Images.js'`;
 // ... code
  picture: {
    type: String,
    autoform: {
      afFieldInput: {
        type: 'fileUpload',
        collection: Images,
      },
    },
  },
```

Or maybe that's weird?

**Comment by dr-dimitru** [comment]
Won't work. `collection` must be a string

**Comment by benjick** [comment]
Ah, okay, I understand

**Comment by dr-dimitru** [comment]
Hi @benjick ,
Should be fixed in v1.0.1, please check on your end.

**Comment by benjick** [comment]
Getting this on page load:

```
Exception in template helper: TypeError: Cannot read property 'findOne' of undefined
    at Object.uploadedFile (http://localhost:3000/packages/ostrio_autoform-files.js?hash=91aa477b035bbde1bef62a3ba0accd49de67f154:149:56)
    at http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:2994:16
    at http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:1653:16
    at http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:3046:66
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:3687:12)
    at http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:3045:27
    at Object.Spacebars.call (http://localhost:3000/packages/spacebars.js?hash=65db8b6a8e3fca189b416de702967b1cb83d57d5:172:18)
    at http://localhost:3000/packages/ostrio_autoform-files.js?hash=91aa477b035bbde1bef62a3ba0accd49de67f154:72:22
    at .<anonymous> (http://localhost:3000/packages/spacebars.js?hash=65db8b6a8e3fca189b416de702967b1cb83d57d5:264:18)
    at http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:1875:20
```

and then when I select an image:

```
fileUpload.js:43 Uncaught TypeError: Cannot read property 'insert' of undefined
```

Using version `1.0.1`

**Comment by benjick** [comment]
Btw, this is with the original code I posted, should I change to anything?

**Comment by dr-dimitru** [comment]
@benjick looks good to me

**Comment by dr-dimitru** [comment]
@benjick have you solved it?

**Comment by benjick** [comment]
I'm without computer for now, but you can close it I guess, I will try when
I get back from vacation

**Comment by dr-dimitru** [comment]
@benjick it is closed. Okay, just let m know when you will be able to test it.

Have good vacation time 🎉 🎉 🎉 🎉 🎉

**Comment by aposidelov** [comment]
Hi, I have a similar errors as @benjick posted in last message:

`Exception in template helper: TypeError: Cannot read property 'findOne' of undefined
    at Object.uploadedFile (http://localhost:3000/packages/ostrio_autoform-files.js?hash=fd25b6ceb186949bd4d67932e48c21238e70b778:219:56)
    at http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:2994:16
    ...`

and also error after trying to upload image:

`fileUpload.js:64 Uncaught TypeError: Cannot read property 'insert' of undefined`

I have file collection in separate file and import it into schema of another collection
images.js:
```javascript
export const Images = new FilesCollection({
  collectionName: 'Images',
  ...
});
```
and
products.js:
```javascript
import { Images } from './images.js';
...
var ss = new SimpleSchema({
	title: {
		type: String,
		label: 'Title',
	},	
	picture: {
    type: String,
    autoform: {
      afFieldInput: {
        type: 'fileUpload',
        collection: 'Images',
        //uploadTemplate: 'uploadField', // <- Optional
        //previewTemplate: 'uploadPreview' // <- Optional
      }
    }
  }
  },
```

**Comment by dr-dimitru** [comment]
@aposidelov 

`Images` variable must be in global scope

**Comment by aposidelov** [comment]
can you advice what is best way to put File collection in global scope in context of autoform and imports? I check a Demo example. file collection resides in lib file and have a name Collections.files . But I suppose this name is not good to use in autoform

**Comment by dr-dimitru** [comment]
This should work:
```jsx
export const Images = new FilesCollection({
  collectionName: 'Images',
  ...
});
window.Images = Images;
```

**Comment by aposidelov** [comment]
window.Images = Images; throw _window is not defined_ warning but it works OK by using **this** instead of **window**:
```javascript
export const Images = new FilesCollection({
  collectionName: 'Images',
  ...
});
this.Images = Images;
```
so I can use `import { Images } from '../imports/collections/images.js';` in the files where I need an access to file collection and use just `import '../imports/collections/images.js';` in autoform schema file.
Also I noticed that publish example from package page doesn't return any data from file collection:
```javascript

Meteor.publish('files.images.all', function () {
  return Images.collection.find({});
});
```
but varint from main package works OK:
```javascript
Meteor.publish('files.images.all', function () {
  return Images.find().cursor;
});
```
Thank you for help!

**Comment by dr-dimitru** [comment]
> Also I noticed that publish example from package page doesn't return any data from file collection

Yesterday other developer reported what `Images.collection.find({})` was working for him instead of `Images.find().cursor`. So it's opposite to you. Weird condition. I'll take a look on this behaviour.

**Comment by larzKke** [comment]
Hello, 
I had the same issue like @benjick and resolved with @aposidelov answer but now when I choose a file to upload I got a new err: 
```
Exception in delivering result of invoking '_FilesCollectionStart_Images': TypeError: Cannot read property '_resolvedSchema' of undefined
```
METEOR@1.4.1.1
ostrio:autoform-files@1.0.7
ostrio:cookies@2.0.5
ostrio:files@1.7.3

**Comment by dr-dimitru** [comment]
@larzKke are you using TS?

**Comment by larzKke** [comment]
@dr-dimitru no, I'm not using TS. 

The error occurs when I only choose a file not even submit the form.

here my code:
```
//Images.JS

export const Images = new FilesCollection({
  collectionName: 'Images',
  allowClientCode: false, // Disallow remove files from Client,
  onBeforeUpload: function (file) {
    // Allow upload files under 10MB, and only in png/jpg/jpeg formats
    if (file.size <= 10485760 && /png|jpg|jpeg/i.test(file.ext)) {
      return true;
    } else {
      return 'Please upload image, with size equal or less than 10MB';
    }
  }
});

this.Images = Images;

export default Images;

```
and
```
//Product.js

import { Images } from './Images.js';

Products = new Mongo.Collection('products');

Products.allow({
    insert: function() {
        return isAdmin();
    },
    update: function() {
        return isAdmin();
    },
    remove: function() {
        return isAdmin();
    }
});

ProductSchema = new SimpleSchema({
    name: {
        type: String,
        label: 'Name'
    },
    picture: {
      type: String,
      autoform: {
        afFieldInput: {
          type: 'fileUpload',
          collection: 'Images'
          // uploadTemplate: 'uploadField', // <- Optional
          // previewTemplate: 'uploadPreview' // <- Optional
        }
      }
    }
});

Products.attachSchema(ProductSchema);


```

**Comment by aposidelov** [comment]
@larzKke 
1) Images.js - remove 
**export default Images;**
2) Product.js - use 
**import './Images.js';**
instead of
**import { Images } from './Images.js';**

**Comment by larzKke** [comment]
@aposidelov sorry, not working. I also create a new meteor app from scratch with one file without success:

```
var Images = new FilesCollection({
  collectionName: 'Images',
  allowClientCode: false, // Disallow remove files from Client,
  onBeforeUpload: function (file) {
    // Allow upload files under 10MB, and only in png/jpg/jpeg formats
    if (file.size <= 10485760 && /png|jpg|jpeg/i.test(file.ext)) {
      return true;
    } else {
      return 'Please upload image, with size equal or less than 10MB';
    }
  }
})

if (Meteor.isClient) {
  Meteor.subscribe('files.images.all');
}

if (Meteor.isServer) {
  Meteor.publish('files.images.all', function () {
    return Images.collection.find({});
  });

}

this.Images = Images;




Posts = new Meteor.Collection('posts');
PostsSchema = new SimpleSchema({
  title: {
    type: String,
    max: 60
  },
  picture: {
    type: String,
    optional: true,
    autoform: {
      afFieldInput: {
        type: 'fileUpload',
        collection: 'Images'
        // uploadTemplate: 'uploadField' // <- Optional
        // previewTemplate: 'uploadPreview' // <- Optional
      }
    }
  }
});

Posts.allow({
  insert: function() {
      return true
  },
  update: function() {
      return true
  },
  remove: function() {
      return true
  }
});

Posts.attachSchema(PostsSchema);

```

**Comment by dr-dimitru** [comment]
@larzKke error comes form method `_FilesCollectionStart_Images `, there is should be an error on Server's console. Could you post it too?

**Comment by larzKke** [comment]
@dr-dimitru no there is no server error, only client side:

```
debug.js:41 Exception in delivering result of invoking '_FilesCollectionStart_Images': TypeError: Cannot read property '_resolvedSchema' of undefined
    at Object.autoFormGetValidationContext [as getValidationContext] (http://localhost:3000/packages/aldeed_autoform.js?hash=bc39be6ca27d0c59949383895549e303297ced7f:2417:16)
    at FileUpload.<anonymous> (http://localhost:3000/packages/ostrio_autoform-files.js?hash=8a3eda0832fcfc9a72e8074bb2edc747305799b4:254:18)
    at FileUpload.emitEvent (http://localhost:3000/packages/ostrio_files.js?hash=eac8f11677fb29a8441222e6526862598932dfd7:481:42)
    at UploadInstance.module.runModuleSetters.FilesCollection._UploadInstance.Meteor.isClient.UploadInstance.end (http://localhost:3000/packages/ostrio_files.js?hash=eac8f11677fb29a8441222e6526862598932dfd7:2807:21)
    at UploadInstance.emitEvent (http://localhost:3000/packages/ostrio_files.js?hash=eac8f11677fb29a8441222e6526862598932dfd7:481:42)
    at handleStart (http://localhost:3000/packages/ostrio_files.js?hash=eac8f11677fb29a8441222e6526862598932dfd7:3059:16)
    at MethodInvoker._callback (http://localhost:3000/packages/meteor.js?hash=ae8b8affa9680bf9720bd8f7fa112f13a62f71c3:1105:22)
    at MethodInvoker._maybeInvokeCallback (http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:3557:12)
    at MethodInvoker.receiveResult (http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:3577:10)
    at Connection._livedata_result (http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:4736:9)
```

**Comment by dr-dimitru** [comment]
@larzKke 
 1. what version of AutoForm you're on?
 2. Is `AutoForm` at global scope?

**Comment by larzKke** [comment]
@dr-dimitru 
_aldeed:autoform@5.8.1
aldeed:collection2@2.3.1
aldeed:simple-schema@1.1.0_

here is a blank [repo](https://github.com/larzKke/uploadTest) with the error. `AutoForm` is not in global scope. Is this required?

**Comment by dr-dimitru** [comment]
> here is a blank repo with the error. AutoForm is not in global scope. Is this required?

Referring to sample code at this lib - yes.
And this should be your issue

**Comment by larzKke** [comment]
@dr-dimitru sorry, can u tell me how to do this? 
I changed the code exactly like in your example ([repo](https://github.com/larzKke/uploadTest/blob/master/lib/main.js)) and get the same error again.

**Comment by dr-dimitru** [comment]
@larzKke idk why it's not in global scope, at least it should be. It might be caused by `ecmascript` package.

Try to bind it to `this` as you do with `Images`, like: `this.AutoForm = AutoForm ;`

**Comment by larzKke** [comment]
@dr-dimitru I got it! 

I changed 
`var Images = new FilesCollection({...`
to 
`this.Images = new FilesCollection({...`

and everything is working fine! strange, but thanks for your help anyway!!! 👍

**Comment by dr-dimitru** [comment]
@larzKke hooray! Glad you've solved it. Thank you for choosing this lib

**Comment by i-siddiq** [comment]
having similar issues, made changes to code according to above instructions but still getting errors. my code is as follows.

```javascript
//images.js
this.Images = new FilesCollection({
  debug: true,
  collectionName: 'Images',
  allowClientCode: false, // Disallow remove files from Client,
  onbeforeunloadMessage: function () {
  return 'Upload is still in progress! Upload will be aborted if you leave this page!';
  },
  onBeforeUpload: function (file) {
    // Allow upload files under 10MB, and only in png/jpg/jpeg formats
    if (file.size <= 10485760 && /png|jpg|jpeg/i.test(file.ext)) {
      return true;
    } else {
      return 'Please upload image, with size equal or less than 10MB';
    }
  }
});

if (Meteor.isClient) {
  Meteor.subscribe('files.images.all');
}

if (Meteor.isServer) {
  Meteor.publish('files.images.all', function () {
    return Images.collection.find({});
  });
  Images.allow({
    insert: function() {
      return true;
    },
    update: function() {
      return true;
    },
    remove: function() {
      return true;
    }
  });
}
```

```javascript
//profiles.js
import './images.js';
Profiles = new Mongo.Collection('profiles');
if (Meteor.isServer) {
  Profiles.allow({
    insert: function (userId, doc) {
      return true;
    },
    update: function (userId, doc, fieldNames, modifier) {
      return true;
    },
    remove: function (userId, doc) {
      return true;
    }
  });
}

images = new SimpleSchema({
  title: {
    type: String,
    label: "Title",
    max: 60,
  },
  profilePic: {
    type: String,
    label: "Profile Picture",
    autoform: {
      afFieldInput: {
        type: 'fileUpload',
        collection: 'Images'
      }
    }
  }
});
Profiles.attachSchema(images);
```

on server I get these errors.

> => Meteor server restarted
> I20161012-03:02:20.962(3)? Kadira: Successfully connected
> I20161012-03:03:23.624(3)? [FilesCollection] [File Start Method] wizard-profile.jpg - qmQYephChcYGY4d6j
> I20161012-03:03:23.637(3)? [FilesCollection] [Upload] [Start Method] Got #-1/2 chunks, dst: wizard-profile.jpg
> I20161012-03:03:23.973(3)? [FilesCollection] [Abort Method]: qmQYephChcYGY4d6j - undefined

on client console I get these errors.

> ostrio_files.js?hash=eac8f11…:2538 [FilesCollection] [findOne({"_id":false}, undefined)]
> ostrio_files.js?hash=eac8f11…:2628 [FilesCollection] [insert()]
> ostrio_files.js?hash=eac8f11…:3115 [FilesCollection] [insert] [Tracker] [continue]
> ostrio_files.js?hash=eac8f11…:3223 [FilesCollection] [insert] [.continue()]
> ostrio_files.js?hash=eac8f11…:3146 [FilesCollection] [insert] using WebWorkers
> ostrio_files.js?hash=eac8f11…:3057 [FilesCollection] [_Start] Error: errorClass {error: 403, reason: "Please upload image, with size equal or less than 10MB", details: undefined, message: "Please upload image, with size equal or less than 10MB [403]", errorType: "Meteor.Error"}handleStart @ ostrio_files.js?hash=eac8f11…:3057(anonymous function) @ dynamics_browser.js:51_maybeInvokeCallback @ livedata_connection.js:446receiveResult @ livedata_connection.js:466_livedata_result @ livedata_connection.js:1625(anonymous function) @ ddp.js:133onMessage @ livedata_connection.js:274(anonymous function) @ stream_client_sockjs.js:172_.each._.forEach @ underscore.js:105self.socket.onmessage @ stream_client_sockjs.js:171REventTarget.dispatchEvent @ sockjs-0.3.4.js:87SockJS._dispatchMessage @ sockjs-0.3.4.js:1072SockJS._didMessage @ sockjs-0.3.4.js:1130that.ws.onmessage @ sockjs-0.3.4.js:1277
> ostrio_files.js?hash=eac8f11…:2796 insert wizard-profile.jpg: 340.888ms
> ostrio_files.js?hash=eac8f11…:2803 [FilesCollection] [insert] [end] Error: errorClass {error: 403, reason: "Please upload image, with size equal or less than 10MB", details: undefined, message: "Please upload image, with size equal or less than 10MB [403]", errorType: "Meteor.Error"}module.runModuleSetters.FilesCollection._UploadInstance.Meteor.isClient.UploadInstance.end @ ostrio_files.js?hash=eac8f11…:2803emitEvent @ event-emitter.jsx:380handleStart @ ostrio_files.js?hash=eac8f11…:3059(anonymous function) @ dynamics_browser.js:51_maybeInvokeCallback @ livedata_connection.js:446receiveResult @ livedata_connection.js:466_livedata_result @ livedata_connection.js:1625(anonymous function) @ ddp.js:133onMessage @ livedata_connection.js:274(anonymous function) @ stream_client_sockjs.js:172_.each._.forEach @ underscore.js:105self.socket.onmessage @ stream_client_sockjs.js:171REventTarget.dispatchEvent @ sockjs-0.3.4.js:87SockJS._dispatchMessage @ sockjs-0.3.4.js:1072SockJS._didMessage @ sockjs-0.3.4.js:1130that.ws.onmessage @ sockjs-0.3.4.js:1277
> ostrio_files.js?hash=eac8f11…:3246 [FilesCollection] [insert] [.abort()]
> ostrio_files.js?hash=eac8f11…:3212 [FilesCollection] [insert] [.pause()]
> ostrio_files.js?hash=eac8f11…:3255 insert wizard-profile.jpg: 357.555ms
> debug.js:41 Exception in delivering result of invoking '_FilesCollectionStart_Images': TypeError: Cannot read property '_resolvedSchema' of undefined
>     at Object.autoFormGetValidationContext [as getValidationContext] (http://localhost:3000/packages/aldeed_autoform.js?hash=bc39be6ca27d0c59949383895549e303297ced7f:2417:16)
>     at FileUpload.<anonymous> (http://localhost:3000/packages/ostrio_autoform-files.js?hash=8a3eda0832fcfc9a72e8074bb2edc747305799b4:254:18)
>     at FileUpload.emitEvent (http://localhost:3000/packages/ostrio_files.js?hash=eac8f11677fb29a8441222e6526862598932dfd7:481:42)
>     at UploadInstance.module.runModuleSetters.FilesCollection._UploadInstance.Meteor.isClient.UploadInstance.end (http://localhost:3000/packages/ostrio_files.js?hash=eac8f11677fb29a8441222e6526862598932dfd7:2807:21)
>     at UploadInstance.emitEvent (http://localhost:3000/packages/ostrio_files.js?hash=eac8f11677fb29a8441222e6526862598932dfd7:481:42)
>     at handleStart (http://localhost:3000/packages/ostrio_files.js?hash=eac8f11677fb29a8441222e6526862598932dfd7:3059:16)
>     at MethodInvoker._callback (http://localhost:3000/packages/meteor.js?hash=ae8b8affa9680bf9720bd8f7fa112f13a62f71c3:1105:22)
>     at MethodInvoker._maybeInvokeCallback (http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:3557:12)
>     at MethodInvoker.receiveResult (http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:3577:10)
>     at Connection._livedata_result (http://localhost:3000/packages/ddp-client.js?hash=27502404fad7fc072e57e8b0b6719f40d92709c7:4736:9)
> 

Cant get what is wrong, any help plz..

**Comment by dr-dimitru** [comment]
@i-siddiq 
Upload is aborted on `onBeforeUpload` remove it for test purposes.

**Comment by i-siddiq** [comment]
@dr-dimitru 
I removed the onBeforeUpload portion. The file upload works except that I dont see a assets/app/uploads/Images/ directory and any thing inside it. The collections do get updated. here it is;
```json
//Images Collection
{
  "_id": "vEvffA58vwR2EDYY5",
  "name": "tim_80x80.png",
  "extension": "png",
  "path": "assets/app/uploads/Images/vEvffA58vwR2EDYY5.png",
  "meta": {},
  "type": "image/png",
  "size": 4821,
  "versions": {
    "original": {
      "path": "assets/app/uploads/Images/vEvffA58vwR2EDYY5.png",
      "size": 4821,
      "type": "image/png",
      "extension": "png"
    }
  },
  "isVideo": false,
  "isAudio": false,
  "isImage": true,
  "isText": false,
  "isJSON": false,
  "isPDF": false,
  "_storagePath": "assets/app/uploads/Images",
  "_downloadRoute": "/cdn/storage",
  "_collectionName": "Images",
  "userId": "RKE2tyKEWKqZQAuyy",
  "public": false
}
```
Server debug output.

> => Client modified -- refreshing
> 
> 
> I20161012-20:36:35.026(3)? [FilesCollection] [File Start Method] tim_80x80.png - vEvffA58vwR2EDYY5
> I20161012-20:36:35.044(3)? [FilesCollection] [Upload] [Start Method] Got #-1/1 chunks, dst: tim_80x80.png
> 
> I20161012-20:36:35.228(3)? [FilesCollection] [Upload] [DDP] Got #1/1 chunks, dst: tim_80x80.png
> 
> I20161012-20:36:35.254(3)? [FilesCollection] [Upload] [DDP] Got #-1/1 chunks, dst: tim_80x80.png
> 
> I20161012-20:36:35.259(3)? [FilesCollection] [Upload] [finish(ing)Upload] -> assets/app/uploads/Images/vEvffA58vwR2EDYY5.png
> 
> I20161012-20:36:35.290(3)? [FilesCollection] [Upload] [finish(ed)Upload] -> assets/app/uploads/Images/vEvffA58vwR2EDYY5.png
> 
> I20161012-20:36:35.306(3)? [FilesCollection] [_preCollectionCursor.observeChanges] [removed]: vEvffA58vwR2EDYY5
> 
> I20161012-20:36:35.420(3)? [FilesCollection] [download(/cdn/storage/Images/vEvffA58vwR2EDYY5/original/vEvffA58vwR2EDYY5.png, original)]
> 
> I20161012-20:36:35.427(3)? [FilesCollection] [serve(assets/app/uploads/Images/vEvffA58vwR2EDYY5.png, original)] [200]

chrome console .

> ostrio_files.js?hash=eac8f11…:2538[FilesCollection] [findOne({"_id":false}, undefined)]
> 3ostrio_files.js?hash=eac8f11…:2538 [FilesCollection] [findOne({"_id":false}, undefined)]
> ostrio_files.js?hash=eac8f11…:2628 [FilesCollection] [insert()]
> ostrio_files.js?hash=eac8f11…:3115 [FilesCollection] [insert] [Tracker] [continue]
> ostrio_files.js?hash=eac8f11…:3223 [FilesCollection] [insert] [.continue()]
> ostrio_files.js?hash=eac8f11…:3146 [FilesCollection] [insert] using WebWorkers
> ostrio_files.js?hash=eac8f11…:2845 loadFile tim_80x80.png: 226.388ms
> ostrio_files.js?hash=eac8f11…:2796 insert tim_80x80.png: 326.105ms
> 2ostrio_files.js?hash=eac8f11…:2538 [FilesCollection] [findOne({"_id":"vEvffA58vwR2EDYY5"}, undefined)]
> ostrio_files.js?hash=eac8f11…:777 [FilesCollection] [FileCursor] [link(undefined)]
> ostrio_files.js?hash=eac8f11…:3726 [FilesCollection] [link(vEvffA58vwR2EDYY5, original)]
> ostrio_files.js?hash=eac8f11…:2538 [FilesCollection] [findOne({"_id":"vEvffA58vwR2EDYY5"}, undefined)]
> ostrio_files.js?hash=eac8f11…:777 [FilesCollection] [FileCursor] [link(undefined)]
> ostrio_files.js?hash=eac8f11…:3726 [FilesCollection] [link(vEvffA58vwR2EDYY5, original)]
> ostrio_files.js?hash=eac8f11…:2538 [FilesCollection] [findOne({"_id":"vEvffA58vwR2EDYY5"}, undefined)]
> ostrio_files.js?hash=eac8f11…:777 [FilesCollection] [FileCursor] [link(undefined)]
> ostrio_files.js?hash=eac8f11…:3726 [FilesCollection] [link(vEvffA58vwR2EDYY5, original)]
> ostrio_files.js?hash=eac8f11…:2538 [FilesCollection] [findOne({"_id":"vEvffA58vwR2EDYY5"}, undefined)]
> ostrio_files.js?hash=eac8f11…:777 [FilesCollection] [FileCursor] [link(undefined)]
> ostrio_files.js?hash=eac8f11…:3726 [FilesCollection] [link(vEvffA58vwR2EDYY5, original)]
> ostrio_files.js?hash=eac8f11…:2538 [FilesCollection] [findOne({"_id":"vEvffA58vwR2EDYY5"}, undefined)]
> ostrio_files.js?hash=eac8f11…:777 [FilesCollection] [FileCursor] [link(undefined)]
> ostrio_files.js?hash=eac8f11…:3726 [FilesCollection] [link(vEvffA58vwR2EDYY5, original)]
>

**Comment by dr-dimitru** [comment]
> I removed the onBeforeUpload portion. The file upload works except that I dont see a assets/app/uploads/Images/ directory and any thing inside it.

It's inside `.meteor/` of your running app.
Read the FAQ at readme. And update to the v1.7.4

**Comment by i-siddiq** [comment]
update to v1.7.4 worked for me. I will post if I get any other errors. thanks @dr-dimitru
