### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by epos** [VeliovGroup/meteor-autoform-file#7]
When building for Linux with Meteor 1.4.0.1 or 1.4.1 the build fails.

Steps to reproduce:
meteor add ostrio:autoform-files
meteor build ../builtlnx --architecture os.linux.x86_64

Error message:
C:\Users\[...]\AppData\Local\.meteor\packages\standard-minifier-js\1.1.8\plugin.
minifyStdJS.os\npm\node_modules\meteor\minifier-js\node_modules\meteor\minifier-
js\node_modules\uglify-js\lib\parse.js:196:18:
Unexpected token: punc ())
at new JS_Parse_Error
(C:\Users\[...]\AppData\Local\.meteor\packages\standard-minifier-js\1.1.8\plugin
.minifyStdJS.os\npm\node_modules\meteor\minifier-js\node_modules\meteor\minifier
-js\node_modules\uglify-js\lib\parse.js:196:18)
at js_error
(C:\Users\[...]\AppData\Local\.meteor\packages\standard-minifier-js\1.1.8\plugin
.minifyStdJS.os\npm\node_modules\meteor\minifier-js\node_modules\meteor\minifier
-js\node_modules\uglify-js\lib\parse.js:204:11)
at croak
(C:\Users\[...]\AppData\Local\.meteor\packages\standard-minifier-js\1.1.8\plugin
.minifyStdJS.os\npm\node_modules\meteor\minifier-js\node_modules\meteor\minifier
-js\node_modules\uglify-js\lib\parse.js:675:9)
at token_error
(C:\Users\[...]\AppData\Local\.meteor\packages\standard-minifier-js\1.1.8\plugin
.minifyStdJS.os\npm\node_modules\meteor\minifier-js\node_modules\meteor\minifier
-js\node_modules\uglify-js\lib\parse.js:683:9)
at unexpected
(C:\Users\[...]\AppData\Local\.meteor\packages\standard-minifier-js\1.1.8\plugin
.minifyStdJS.os\npm\node_modules\meteor\minifier-js\node_modules\meteor\minifier
-js\node_modules\uglify-js\lib\parse.js:689:9)
at expr_atom
(C:\Users\[...]\AppData\Local\.meteor\packages\standard-minifier-js\1.1.8\plugin
.minifyStdJS.os\npm\node_modules\meteor\minifier-js\node_modules\meteor\minifier
-js\node_modules\uglify-js\lib\parse.js:1184:13)
at maybe_unary
(C:\Users\[...]\AppData\Local\.meteor\packages\standard-minifier-js\1.1.8\plugin
.minifyStdJS.os\npm\node_modules\meteor\minifier-js\node_modules\meteor\minifier
-js\node_modules\uglify-js\lib\parse.js:1358:19)
at expr_ops
(C:\Users\[...]\AppData\Local\.meteor\packages\standard-minifier-js\1.1.8\plugin
.minifyStdJS.os\npm\node_modules\meteor\minifier-js\node_modules\meteor\minifier
-js\node_modules\uglify-js\lib\parse.js:1393:24)
at maybe_conditional
(C:\Users\[...]\AppData\Local\.meteor\packages\standard-minifier-js\1.1.8\plugin
.minifyStdJS.os\npm\node_modules\meteor\minifier-js\node_modules\meteor\minifier
-js\node_modules\uglify-js\lib\parse.js:1398:20)
at maybe_assign
(C:\Users\[...]\AppData\Local\.meteor\packages\standard-minifier-js\1.1.8\plugin
.minifyStdJS.os\npm\node_modules\meteor\minifier-js\node_modules\meteor\minifier
-js\node_modules\uglify-js\lib\parse.js:1422:20)

**Comment by epos** [comment]
PS: thanks for that **GREAT** package.

**Comment by dr-dimitru** [comment]
Hi @epos ,

Somehow I've missed this issue. There is was few package updates since this issue was created.
Could you please update, and ping me back if issue still exists?

**Comment by epos** [comment]
Thanks dr-dimitru, I'm going to test it today and get back to you.

**Comment by dr-dimitru** [comment]
Meanwhile there is newer release, please make sure you've updated to the latest available version

**Comment by epos** [comment]
Sorry I couldn't try earlier. I just tried again after updating to Meteor 1.4.1.1 and the Linux build now works fine. Thank you!

**Comment by dr-dimitru** [comment]
@epos 👍 

Please support this package by start on [GitHub](https://github.com/VeliovGroup/meteor-autoform-file) and [Atmosphere](https://atmospherejs.com/ostrio/autoform-files)

**Comment by epos** [comment]
Just did, thanks!
