### ISSUE TITLE
Deactivate uploadImageDemo

### ISSUE THREAD

**Issue by AdrianAbba** [VeliovGroup/meteor-autoform-file#8]
Hey :)

It is possible to deactivate the uploadImageDemo methode?
after uploading a image i still wanna see the file choose button.

https://files.gitter.im/VeliovGroup/Meteor-Files/zDVD/bild.jpg
https://files.gitter.im/VeliovGroup/Meteor-Files/BHRO/cccccc.png

My Goal is, clicking on the circle picture (avatar), the file choose window open and after uploading the image it will change to the new picture.

**Comment by dr-dimitru** [comment]
@AdrianAbba 

You you can create custom template with file name and reset button. Take a [`uploadFileDemo.html `](https://github.com/VeliovGroup/meteor-autoform-file/blob/master/lib/client/uploadFileDemo.html) as example, change it to fit your needs and pass its name to `previewTemplate `

**Comment by dr-dimitru** [comment]
Other wise I recommend to you not use auto firm package and stick to [Meteor-Files](https://github.com/VeliovGroup/Meteor-Files) lib.

**Comment by dr-dimitru** [comment]
Hey @AdrianAbba , any news on your end?

**Comment by AdrianAbba** [comment]
yeah :D 

I stopped to use the autoform package and used your [https://github.com/VeliovGroup/Meteor-Files](url) files :)
{{> uploadForm}}  was enough .

My next step is to put the {{> uploadForm}} template behind my avatarImage, if the currentUser is clicking on his Picture he should be able to change it. :D

But u can Close this issue

thx =)

**Comment by dr-dimitru** [comment]
Thank you for update on this one
